version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/sources/
    depends_on:
      - redis
    links:
      - redis

  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: .
    command: ["celery", "-A", "tasks", "worker", "-l", "info"]
    depends_on:
      - app
      - redis
    links:
      - redis
    volumes:
      - .:/sources/
